server:
   port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/family?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 147258369

    type: com.alibaba.druid.pool.DruidDataSource
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
  mail:
    host: smtp.qq.com
    port: 587
    username: wu2690144925@qq.com
    password: eyrnzdpfzhffdega
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

pagehelper:
    helperDialect: mysql
    supportMethodsArguments: true
    params: count=countSql

mybatis:
  type-aliases-package: com.example.account.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

front:
  addr: http://localhost:8088

